name: isar_crdt
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

# Add regular dependencies here.
# dependencies:
# path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
  build_runner:
  isar_generator:
dependencies:
  isar: ^3.1.0+1
  isar_flutter_libs: ^3.1.0+1
  meta: ^1.9.1
  quiver: ^3.2.1
