name: isar_crdt_test
description: A sample command-line application.
version: 0.1.0
publish_to: none
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.0.6

dependencies:
  isar: ^3.1.0+1
  isar_crdt:
    path: ../isar_crdt
  isar_flutter_libs: ^3.1.0+1
  quiver: ^3.2.1

dev_dependencies:
  build_runner: ^2.4.6
  isar_crdt_generator:
    path: ../isar_crdt_generator
  lints: ^2.0.0
  test: ^1.21.0
  very_good_analysis: ^5.1.0

dependency_overrides:
  isar_crdt:
    path: ../isar_crdt
  isar_crdt_generator:
    path: ../isar_crdt_generator
