name: ci

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

env:
  FLUTTER_VERSION: 3

jobs:
  ci:
    name: Continuous integration
    runs-on: ubuntu-latest
    steps:
      # Setup
      - uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: ${{ env.FLUTTER_VERSION }}

      # Install dependencies
      - name: isar-crdt install dependencies
        run: dart pub get
        working-directory: packages/isar_crdt
      - name: isar-crdt-generator install dependencies
        run: dart pub get
        working-directory: packages/isar_crdt_generator
      - name: isar-crdt-test install dependencies
        run: dart pub get
        working-directory: packages/isar_crdt_test

      # Formatting
      - name: Check formatting
        run: dart format -o none --set-exit-if-changed  .

      # Linting
      - name: Linting
        run: dart analyze --fatal-warnings
        if: ${{ false }} #TODO: remove once finished with documenting public API

      # Testing
      - name: Test isar-crdt package
        working-directory: packages/isar_crdt
        run: dart test
      - name: E2E tests
        working-directory: packages/isar_crdt_test
        run: |
          dart run build_runner build
          dart test
